### ISSUE TITLE
Question: how does the changes in 3.x affects tastypie-rethink?

### ISSUE THREAD

**Issue by nexbit** [esatterwhite/node-tastypie#13]
I've made some modifications/fixes to my fork of tastypie-rethink.. as the author of both node-tastypie and tasypie-rethink do you know if something needs changes in the latter after the 3.x release of node-tastypie?

Thx

**Comment by esatterwhite** [comment]
Yes. The major change was that the top level methods like `post_list`, `put_detail`, etc

call `deserializse` the [rethink resource](https://github.com/esatterwhite/tastypie-rethink/blob/master/lib/resource/index.js#L226) is still calling that internally inside of `create_object`, `update_object`.

It doesn't need to do that anymore. I don't think it will actually throw an error, but it was a fundamental change, so major version.


I was planning one bringing the sub-projects up to date soon. You are welcome to give it a shot

**Comment by nexbit** [comment]
I'll open a separate issue on tastypie-rethink, as I'm a bit confused on what I see there..
