### ISSUE TITLE
Respond with 200(ok) in put_detail and patch_detail

### ISSUE THREAD

**Issue by nexbit** [esatterwhite/node-tastypie#15]
Now the implementation returns `202 (accepted)`, and that it should be used for long running (batch) async operations that will complete sometime in the future (https://httpstatuses.com/202).
A return code of 200 seems to be more standard and better handled by clients.

Thx.

**Comment by esatterwhite** [comment]
Yep, I buy that

**Comment by nexbit** [comment]
More importantly, I think I've found a couple of bugs in that methods, regarding the handling of the returnData options. I'll open a PR to include that and the ok response, so you'll be able to test them.

**Comment by esatterwhite** [comment]
@nexbit haha, already a step ahead. I did the 200 bit in master.
