### ISSUE TITLE
How a readonly field is supposed to work

### ISSUE THREAD

**Issue by nexbit** [esatterwhite/node-tastypie#17]
Hi
if I define a field as `readonly` I'd have a simple expectation: that field should never pass down the hydration pipeline, and should never reach my persistence logic.
But, at least in my every attempt, that attribute seems to be ignored, and users of my API are able to pass values to readonly fields, causing unwanted behaviours..
Is it a bug, a missing feature, or something that should be handled in some other way? The idea of a readonly field is a useful one, but only if it's been handled by the core..

Thx

**Comment by esatterwhite** [comment]
`full_hydrate` skips over readonly fields

https://github.com/esatterwhite/node-tastypie/blob/master/lib/resource/index.js#L653

**Comment by nexbit** [comment]
Yes but I didn't grasp the inner working of the hydration/dehydration pipeline, and everything was terribly wrong :/
It is definitely a point to improve in docs.
Basically I was using bundle.object everywhere, instead (I think) the correct way to extend a resource is:

* set the `objectTpl` option to your Model/DTO class ctor func (in my case it's a dto class)
* in methods like `create_object` call `full_hydrate` and let the function to ctor the `objectTpl` for you
* if you need to process some fields during hydration, override `hydrate` or define specific `hydrate_field` functions, but use bundle.data to do the processing, not bundle.object as that is the result of the hydration (I was doing a mix of things).
* when `full_hydrate`calls the callback, bundle.object is already an instance of `objectTpl` and is ready to be saved

Does it sound good?
PS: I'm under the impression that `tastypie-rethink` does not follow a standard approach, and I found that it does unnecessary things..

**Comment by esatterwhite** [comment]
Yeah, the docs on hydration / dehydration are lacking.


Yes, that sounds right. The only thing that is different about th rethink resource is it will try to use The Model from the `queryset` property over `objectTpl`, In that aspect, you should never have to set / deal with `objectTpl` at all. Just define a default queryset, and that is it.

What unnecessary things did you observe?

**Comment by esatterwhite** [comment]
@nexbit Could you provide a bit of clarification ? is this behaving differently than documented, or a mis-understanding?

**Comment by nexbit** [comment]
Primarily a misunderstanding.. I'm progressively enhancing my api and discovering things.

I worked primarily with strongly typed languages so far, and started a node.js api project 3 weeks ago, but I used it before to program complex gulp tasks for my front end workflow.
I must confess I find node js code very hard to debug and read, and the lack of a type system plus that callback hell is driving me nuts! I tried typescript, but that's only for your code, it doesn't help when dealing with someone else's code..

Sorry for my ranting ;)

**Comment by esatterwhite** [comment]
@nexbit it does change the way you think about things. I plan to convert this to use generators or async/await

**Comment by esatterwhite** [comment]
@nexbit I would suggest using node-inspector

**Comment by nexbit** [comment]
Unfortunately I already use IntelliJ IDEA that has a good debug support for node.js, but even with that it's nearly impossible to follow the code path, when something bad happens outside your code. Async/parallel debugging is nearly impossible, while it's well (ok, better at least) supported in other langs. And a debugger doesn't alleviate the pain with reading messy callback code. I had good luck with static code analysers in other dynamic langs, like Python, but they simply fail with node.js.
Don't misunderstand me, I do really appreciate your work, and most of the work by JS folks out there, but I'm simply realising that the tooling and the platform as it stands today is not well suited for long-term maintainable code..
If you have something to point me to prove the opposite, well I'll really appreciate it ! ;)

P.

**Comment by nexbit** [comment]
I feel like [this](https://bjouhier.wordpress.com/2014/07/05/tj-leaving-node-js/), maybe I'll investigate that streamline.js for my own code, but the problem remains for the zillions of packages out there, that are simply unreadable.
Go definitely attracts people like me, 'cause it's a mixture of old and new school, and it's very easy to read (I myself contributed to docker-machine code without knowing Go before..).

P.
