### ISSUE TITLE
dehydrate method is not called like the doc says

### ISSUE THREAD

**Issue by nexbit** [esatterwhite/node-tastypie#8]
Doc comment for `dehydrate` method says:

> A final hook to run and last deydration operations before a response is returned

But indeed it is called for *each every field in the resource*. It's rather useless when what you want is really a *final hook before a response is returned*.

I had to change the `full_dehydrate` method with the following code to make the `dehydrate` method do what it says:
```
  , full_dehydrate: function full_dehydrate(obj, bundle, done) {
    var ret = {}
      , fields = this.fields
      , dehydrate = this.dehydrate
      , that = this
      ;

    async.forEachOf(fields, function eachfield(fld, field, cb) {
      fld.dehydrate(obj, function asyncFieldDehy(err, data) {
        ret[field] = data;
        var methodname = 'dehydrate_' + field
          , method = that[methodname]
          ;

        if (method) {
          ret[field] = method.call(that, obj, bundle, ret);
        }

        return cb && cb(err);
      });
    }, function (err) {
      done(err, dehydrate(ret));
    });
  }
```
basically it calls the `done` callback with the result of the `dehydrate` method call, making that method the last one called. Now I can manipulate the response in a single place before returning it to the client..

If you like the change, let me know if I should open a pull request with that code or you want to fix it yourself.
Thx, Paul

**Comment by esatterwhite** [comment]
@nexbit  Yes! good catch, that is a bug when this was converted from sync to async. 

PR welcome
